set -g default-terminal "screen-256color"
unbind r
bind r source-file ~/.config/tmux/tmux.conf
setw -g mouse on
setw -g mode-keys vi
set-window-option -g mode-keys vi

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'dracula/tmux'
# set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jimeh/tmux-themepack'

set -g @themepack 'powerline/double/cyan'
# set -g @dracula-show-powerline true
# set -g @dracula-show-network true
# set -g @dracula-show-cpu-usage true
# set -g @dracula-fixed-location "Atlanta"
# set -g @dracula-day-month false
# set -g @dracula-show-timezone false
# set -g @dracula-military-time true
# set -g @dracula-plugins "network cpu-usage battery weather time"
# set -g @dracula-show-flags true
# set -g @dracula-show-left-icon session
set -g status-position top
# unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse



run '~/.tmux/plugins/tpm/tpm'
